name: Data Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update system packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Docker Compose via apt
        run: |
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Build Docker image
        run: docker build -t data-pipeline .

      - name: Run pipeline
        run: docker-compose run pipeline