name: Data Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose via pip
        run: |
          pip install docker-compose
          docker-compose --version

      - name: Build Docker image
        run: docker build -t data-pipeline .

      - name: Run pipeline
        run: docker-compose run pipeline